name: dart_release_cli
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  dcli: ^1.36.2
  io: ^1.0.4
  markdown: ^7.1.1
  yaml: ^3.1.2


dcli: ^3.0.3
yaml: ^3.1.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
